"""PDF report generation service using WeasyPrint."""

import base64
import json
import logging
import re
from datetime import datetime
from pathlib import Path

from jinja2 import Environment, FileSystemLoader
from sqlalchemy.orm import Session

from app.models.document import DocumentSummary
from app.models.photo import Photo
from app.models.price_analysis import PriceAnalysis
from app.services.storage import get_storage_service

logger = logging.getLogger(__name__)

TEMPLATE_DIR = Path(__file__).parent.parent / "templates" / "report"

REPORT_TRANSLATIONS: dict[str, dict[str, str]] = {
    "cover_tagline": {
        "fr": "Plateforme d'aide a la decision immobiliere",
        "en": "Real estate decision support platform",
    },
    "cover_badge": {
        "fr": "Rapport d'analyse immobiliere",
        "en": "Property Analysis Report",
    },
    "generated_on": {"fr": "Genere le", "en": "Generated on"},
    "property_summary": {"fr": "Fiche du bien", "en": "Property Summary"},
    "address": {"fr": "Adresse", "en": "Address"},
    "city": {"fr": "Ville", "en": "City"},
    "property_type": {"fr": "Type de bien", "en": "Property Type"},
    "asking_price": {"fr": "Prix demande", "en": "Asking Price"},
    "surface_area": {"fr": "Surface", "en": "Surface Area"},
    "rooms": {"fr": "Pieces", "en": "Rooms"},
    "floor": {"fr": "Etage", "en": "Floor"},
    "building_year": {"fr": "Annee de construction", "en": "Building Year"},
    "price_per_sqm": {"fr": "Prix au m2", "en": "Price per sqm"},
    "price_analysis_title": {"fr": "Analyse de prix", "en": "Price Analysis"},
    "estimated_value": {"fr": "Valeur estimee", "en": "Estimated Value"},
    "price_deviation": {"fr": "Ecart de prix", "en": "Price Deviation"},
    "market_avg_sqm": {"fr": "Prix moyen du marche/m2", "en": "Market Avg Price/sqm"},
    "comparable_sales": {"fr": "Ventes comparables", "en": "Comparable Sales"},
    "comparables_count": {"fr": "Ventes comparables", "en": "Comparable Sales"},
    "sale_address": {"fr": "Adresse", "en": "Address"},
    "sale_date": {"fr": "Date", "en": "Date"},
    "sale_price": {"fr": "Prix", "en": "Price"},
    "sale_surface": {"fr": "Surface", "en": "Surface"},
    "sale_price_sqm": {"fr": "Prix/m2", "en": "Price/sqm"},
    "market_trend_title": {"fr": "Tendance du marche", "en": "Market Trend"},
    "year": {"fr": "Annee", "en": "Year"},
    "avg_price_sqm": {"fr": "Prix moyen/m2", "en": "Avg Price/sqm"},
    "yoy_change": {"fr": "Evolution annuelle", "en": "Year-over-Year"},
    "sample_count": {"fr": "Nb ventes", "en": "Sales Count"},
    "confidence": {"fr": "Confiance", "en": "Confidence"},
    "synthesis_title": {"fr": "Synthese documentaire", "en": "Document Synthesis"},
    "risk_level": {"fr": "Niveau de risque", "en": "Risk Level"},
    "annual_costs": {"fr": "Couts annuels", "en": "Annual Costs"},
    "one_time_costs": {"fr": "Couts ponctuels", "en": "One-Time Costs"},
    "summary": {"fr": "Resume", "en": "Summary"},
    "key_findings": {"fr": "Points cles", "en": "Key Findings"},
    "recommendations": {"fr": "Recommandations", "en": "Recommendations"},
    "annual_cost_breakdown": {"fr": "Detail des couts annuels", "en": "Annual Cost Breakdown"},
    "one_time_cost_breakdown": {
        "fr": "Detail des couts ponctuels",
        "en": "One-Time Cost Breakdown",
    },
    "cost_category": {"fr": "Categorie", "en": "Category"},
    "cost_amount": {"fr": "Montant", "en": "Amount"},
    "cost_description": {"fr": "Description", "en": "Description"},
    "redesign_gallery": {"fr": "Galerie de redesigns", "en": "Redesign Gallery"},
    "footer_line": {
        "fr": "Genere par AppArt Agent - {date} - A titre informatif uniquement",
        "en": "Generated by AppArt Agent - {date} - For informational purposes only",
    },
}

COST_KEY_LABELS: dict[str, dict[str, str]] = {
    "charges_copropriete": {"fr": "Charges de copropriete", "en": "Co-ownership charges"},
    "taxe_fonciere": {"fr": "Taxe fonciere", "en": "Property tax"},
    "estimated_energy": {"fr": "Energie estimee", "en": "Estimated energy"},
    "fonds_travaux": {"fr": "Fonds travaux", "en": "Works fund"},
    "other_recurring": {"fr": "Autres charges recurrentes", "en": "Other recurring costs"},
    "assurance": {"fr": "Assurance", "en": "Insurance"},
}


class _TranslationProxy:
    """Dot-accessible translation proxy for Jinja2 templates."""

    def __init__(self, locale: str):
        self._locale = locale

    def __getattr__(self, key: str) -> str:
        entry = REPORT_TRANSLATIONS.get(key)
        if entry is None:
            return key
        return entry.get(self._locale, entry.get("fr", key))


def _format_eur(value) -> str:
    """Format a number as EUR currency."""
    if value is None:
        return "-"
    try:
        num = float(value)
        return f"{num:,.0f} EUR".replace(",", " ")
    except (ValueError, TypeError):
        return "-"


def _format_cost_key(key: str, locale: str = "fr") -> str:
    """Format a cost breakdown key into a human-readable label."""
    entry = COST_KEY_LABELS.get(key)
    if entry:
        return entry.get(locale, entry.get("fr", key))
    return key.replace("_", " ").capitalize()


def sanitize_filename(text: str) -> str:
    """Sanitize a string for use in a filename."""
    clean = re.sub(r"[^\w\s\-]", "", text)
    clean = re.sub(r"\s+", "_", clean.strip())
    return clean[:80]


def _get_jinja_env() -> Environment:
    """Create Jinja2 environment pointing at the templates directory."""
    return Environment(  # nosec B701 - templates render to PDF, not served as HTML
        loader=FileSystemLoader(str(TEMPLATE_DIR)),
        autoescape=False,
    )


def _get_synthesis_data(synthesis) -> tuple[dict | None, list | None]:
    """Extract annual and one-time cost breakdowns from synthesis_data JSON."""
    if not synthesis or not synthesis.synthesis_data:
        return None, None
    try:
        data = (
            json.loads(synthesis.synthesis_data)
            if isinstance(synthesis.synthesis_data, str)
            else synthesis.synthesis_data
        )
    except (json.JSONDecodeError, TypeError):
        return None, None
    annual = data.get("annual_cost_breakdown")
    one_time = data.get("one_time_cost_breakdown")
    return annual, one_time


def _fetch_promoted_redesigns_as_base64(property_id: int, db: Session) -> list[dict]:
    """Fetch promoted redesign photos and convert to base64 data URIs."""
    photos = (
        db.query(Photo)
        .filter(Photo.property_id == property_id, Photo.promoted_redesign_id.isnot(None))
        .all()
    )
    if not photos:
        return []
    storage = get_storage_service()
    result = []
    for photo in photos:
        redesign = photo.promoted_redesign
        if not redesign:
            continue
        try:
            image_bytes = storage.download_file(redesign.storage_key, redesign.storage_bucket)
            b64 = base64.b64encode(image_bytes).decode("utf-8")
            data_uri = f"data:image/jpeg;base64,{b64}"
            result.append(
                {
                    "filename": photo.filename,
                    "room_type": photo.room_type,
                    "data_uri": data_uri,
                }
            )
        except Exception as e:
            logger.warning(f"Failed to fetch redesign image for photo {photo.id}: {e}")
    return result


def generate_full_report_pdf(property_obj, db: Session, locale: str = "fr") -> bytes:
    """Generate a comprehensive PDF report for a property."""
    import weasyprint

    env = _get_jinja_env()
    template = env.get_template("full_report.html")

    price_analysis = (
        db.query(PriceAnalysis).filter(PriceAnalysis.property_id == property_obj.id).first()
    )
    synthesis = (
        db.query(DocumentSummary)
        .filter(DocumentSummary.property_id == property_obj.id, DocumentSummary.category == None)
        .first()
    )

    comparable_sales: list = []
    market_trend = None
    if price_analysis:
        comparable_sales = price_analysis.comparable_sales_json or []
        market_trend = price_analysis.market_trend_json

    annual_cost_breakdown, one_time_cost_breakdown = _get_synthesis_data(synthesis)
    photos_with_redesigns = _fetch_promoted_redesigns_as_base64(property_obj.id, db)
    export_date = datetime.utcnow().strftime("%d/%m/%Y")

    html = template.render(
        property=property_obj,
        price_analysis=price_analysis,
        comparable_sales=comparable_sales,
        market_trend=market_trend,
        synthesis=synthesis,
        annual_cost_breakdown=annual_cost_breakdown,
        one_time_cost_breakdown=one_time_cost_breakdown,
        photos_with_redesigns=photos_with_redesigns,
        export_date=export_date,
        locale=locale,
        t=_TranslationProxy(locale),
        format_eur=_format_eur,
        format_cost_key=lambda k: _format_cost_key(k, locale),
    )

    return weasyprint.HTML(string=html, base_url=str(TEMPLATE_DIR)).write_pdf()


def generate_price_analysis_pdf(property_obj, db: Session, locale: str = "fr") -> bytes:
    """Generate a PDF with only the price analysis section."""
    import weasyprint

    env = _get_jinja_env()
    template = env.get_template("price_analysis.html")

    price_analysis = (
        db.query(PriceAnalysis).filter(PriceAnalysis.property_id == property_obj.id).first()
    )

    comparable_sales: list = []
    market_trend = None
    if price_analysis:
        comparable_sales = price_analysis.comparable_sales_json or []
        market_trend = price_analysis.market_trend_json

    export_date = datetime.utcnow().strftime("%d/%m/%Y")

    html = template.render(
        property=property_obj,
        price_analysis=price_analysis,
        comparable_sales=comparable_sales,
        market_trend=market_trend,
        export_date=export_date,
        locale=locale,
        t=_TranslationProxy(locale),
        format_eur=_format_eur,
        format_cost_key=lambda k: _format_cost_key(k, locale),
    )

    return weasyprint.HTML(string=html, base_url=str(TEMPLATE_DIR)).write_pdf()


def generate_synthesis_pdf(property_obj, db: Session, locale: str = "fr") -> bytes:
    """Generate a PDF with only the document synthesis section."""
    import weasyprint

    env = _get_jinja_env()
    template = env.get_template("synthesis.html")

    synthesis = (
        db.query(DocumentSummary)
        .filter(DocumentSummary.property_id == property_obj.id, DocumentSummary.category == None)
        .first()
    )

    annual_cost_breakdown, one_time_cost_breakdown = _get_synthesis_data(synthesis)
    export_date = datetime.utcnow().strftime("%d/%m/%Y")

    html = template.render(
        property=property_obj,
        synthesis=synthesis,
        annual_cost_breakdown=annual_cost_breakdown,
        one_time_cost_breakdown=one_time_cost_breakdown,
        export_date=export_date,
        locale=locale,
        t=_TranslationProxy(locale),
        format_eur=_format_eur,
        format_cost_key=lambda k: _format_cost_key(k, locale),
    )

    return weasyprint.HTML(string=html, base_url=str(TEMPLATE_DIR)).write_pdf()
